#!/bin/bash
# ##############################################################################
# CLEAN ENVIRONMENT
# Generated by DevUtils CLI (https://github.com/fredlackey/devutils-cli)
# ##############################################################################
#
# Resets the test environment to a clean state.
# Run this before tests to ensure consistent starting conditions.
#
# Usage:
#   ./testing/scripts/clean-env.sh          # Clean current environment
#   ./testing/scripts/clean-env.sh --all    # Also remove Docker volumes
#
# ##############################################################################

set -e

echo "=== Cleaning Test Environment ==="

# Detect if running in container
IN_CONTAINER=false
if [ -f /.dockerenv ] || [ -n "$DOCKER_CONTAINER" ]; then
    IN_CONTAINER=true
fi

# Remove devutils-cli config file
if [ -f "$HOME/.devutils" ]; then
    echo "Removing: $HOME/.devutils"
    rm -f "$HOME/.devutils"
fi

# Remove test SSH keys (only those created by tests)
echo "Removing test SSH keys..."
rm -f ~/.ssh/id_ed25519_test*
rm -f ~/.ssh/id_rsa_test*

# Remove test directories
echo "Removing test directories..."
rm -rf /tmp/test-*

# Clean npm cache (optional, can speed up subsequent installs)
if [ "$1" = "--deep" ]; then
    echo "Cleaning npm cache..."
    npm cache clean --force 2>/dev/null || true
fi

# If running on host (not in container), offer to clean Docker resources
if [ "$IN_CONTAINER" = false ] && [ "$1" = "--all" ]; then
    echo ""
    echo "Cleaning Docker resources..."

    # Check if we're in the right directory
    if [ -f "testing/docker-compose.yml" ]; then
        # Stop and remove containers
        docker compose -f testing/docker-compose.yml down --volumes --remove-orphans 2>/dev/null || true

        # Remove test images (optional)
        echo "Removing test images..."
        docker images --filter "reference=*devutils-cli-test*" -q | xargs -r docker rmi 2>/dev/null || true
    fi
fi

echo ""
echo "Environment cleaned successfully."
echo ""
echo "To rebuild and run tests:"
echo "  docker compose -f testing/docker-compose.yml up --build"
