#!/bin/bash
# ##############################################################################
# MAIN TEST RUNNER
# Generated by DevUtils CLI (https://github.com/fredlackey/devutils-cli)
# ##############################################################################
#
# Runs all test suites in sequence and reports results.
#
# Usage:
#   ./testing/scripts/run-tests.sh           # Run all tests
#   ./testing/scripts/run-tests.sh cli       # Run specific test suite
#
# ##############################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM="${TEST_PLATFORM:-unknown}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Track test results
PASSED=0
FAILED=0
SKIPPED=0

# Print header
print_header() {
    echo ""
    echo -e "${BLUE}##############################################################################${NC}"
    echo -e "${BLUE}# $1${NC}"
    echo -e "${BLUE}##############################################################################${NC}"
    echo ""
}

# Print test result
print_result() {
    local name="$1"
    local status="$2"

    if [ "$status" = "PASS" ]; then
        echo -e "  ${GREEN}[PASS]${NC} $name"
        ((PASSED++))
    elif [ "$status" = "FAIL" ]; then
        echo -e "  ${RED}[FAIL]${NC} $name"
        ((FAILED++))
    else
        echo -e "  ${YELLOW}[SKIP]${NC} $name"
        ((SKIPPED++))
    fi
}

# Run a test script and capture result
run_test_suite() {
    local name="$1"
    local script="$2"

    print_header "Running: $name"

    if [ ! -f "$script" ]; then
        echo -e "${YELLOW}Script not found: $script${NC}"
        print_result "$name" "SKIP"
        return
    fi

    if bash "$script"; then
        print_result "$name" "PASS"
    else
        print_result "$name" "FAIL"
    fi
}

# Clean environment before tests
clean_environment() {
    print_header "Cleaning Test Environment"

    # Remove any existing config
    rm -f ~/.devutils

    # Clean up any test directories
    rm -rf /tmp/test-*

    echo "Environment cleaned."
}

# Main execution
main() {
    local specific_test="$1"

    print_header "DEV-UTILS TEST SUITE"
    echo "Platform: $PLATFORM"
    echo "Node.js:  $(node --version)"
    echo "npm:      $(npm --version)"
    echo "Date:     $(date)"

    # Clean environment first
    clean_environment

    # Define test suites
    declare -A TESTS=(
        ["cli"]="$SCRIPT_DIR/test-cli.sh"
        ["configure"]="$SCRIPT_DIR/test-configure.sh"
        ["ignore"]="$SCRIPT_DIR/test-ignore.sh"
        ["identity"]="$SCRIPT_DIR/test-identity.sh"
        ["install"]="$SCRIPT_DIR/test-install.sh"
    )

    # Run specific test or all tests
    if [ -n "$specific_test" ]; then
        if [ -n "${TESTS[$specific_test]}" ]; then
            run_test_suite "$specific_test" "${TESTS[$specific_test]}"
        else
            echo -e "${RED}Unknown test suite: $specific_test${NC}"
            echo "Available: ${!TESTS[*]}"
            exit 1
        fi
    else
        # Run all tests in order
        for name in cli configure ignore identity install; do
            run_test_suite "$name" "${TESTS[$name]}"
        done
    fi

    # Print summary
    print_header "TEST SUMMARY"
    echo -e "Platform: ${BLUE}$PLATFORM${NC}"
    echo -e "Passed:   ${GREEN}$PASSED${NC}"
    echo -e "Failed:   ${RED}$FAILED${NC}"
    echo -e "Skipped:  ${YELLOW}$SKIPPED${NC}"
    echo ""

    # Exit with error if any tests failed
    if [ "$FAILED" -gt 0 ]; then
        echo -e "${RED}Some tests failed!${NC}"
        exit 1
    else
        echo -e "${GREEN}All tests passed!${NC}"
        exit 0
    fi
}

main "$@"
