#!/bin/bash
# ##############################################################################
# IGNORE COMMAND TESTS
# Generated by DevUtils CLI (https://github.com/fredlackey/devutils-cli)
# ##############################################################################
#
# Tests the gitignore pattern functionality.
#
# ##############################################################################

set -e

echo "=== Ignore Command Tests ==="

TEST_DIR="/tmp/test-ignore-$$"

# Clean up function
cleanup() {
    rm -rf "$TEST_DIR"
}
trap cleanup EXIT

# Create test directory
mkdir -p "$TEST_DIR"
cd "$TEST_DIR"

# Initialize git repository
echo "Creating test git repository..."
git init --quiet

# Test: ignore without git repo (from different directory)
echo "Testing: dev ignore outside git repo"
cd /tmp
if dev ignore node 2>&1 | grep -qi "no git repository\|not found"; then
    echo "  Correctly detected: not in git repository"
else
    echo "  Note: May have found parent git repo"
fi
cd "$TEST_DIR"

# Test: ignore --list
echo "Testing: dev ignore --list"
dev ignore --list | grep -q "node\|macos" || { echo "FAIL: --list should show available technologies"; exit 1; }

# Test: ignore unknown technology
echo "Testing: dev ignore unknown-tech"
if dev ignore unknown-tech-xyz 2>&1 | grep -qi "unknown\|not found\|error"; then
    echo "  Correctly rejected unknown technology"
else
    echo "FAIL: Should reject unknown technology"
    exit 1
fi

# Test: ignore --dry-run
echo "Testing: dev ignore node --dry-run"
dev ignore node --dry-run | grep -q "node_modules\|=== dev-utils" || { echo "FAIL: --dry-run should show patterns"; exit 1; }

# Verify .gitignore not created during dry-run
if [ -f ".gitignore" ]; then
    echo "FAIL: --dry-run should not create .gitignore"
    exit 1
fi

# Test: ignore node (actual)
echo "Testing: dev ignore node"
dev ignore node

# Verify .gitignore created
if [ ! -f ".gitignore" ]; then
    echo "FAIL: .gitignore was not created"
    exit 1
fi

# Verify content
echo "Verifying .gitignore content..."
grep -q "node_modules" .gitignore || { echo "FAIL: Missing node_modules pattern"; exit 1; }
grep -q "=== dev-utils: node ===" .gitignore || { echo "FAIL: Missing start marker"; exit 1; }
grep -q "=== end: node ===" .gitignore || { echo "FAIL: Missing end marker"; exit 1; }

# Test: duplicate detection
echo "Testing: dev ignore node (duplicate)"
OUTPUT=$(dev ignore node 2>&1)
if echo "$OUTPUT" | grep -qi "already present"; then
    echo "  Correctly detected duplicate"
else
    echo "FAIL: Should detect duplicate patterns"
    exit 1
fi

# Verify file wasn't duplicated (count markers)
MARKER_COUNT=$(grep -c "=== dev-utils: node ===" .gitignore)
if [ "$MARKER_COUNT" -ne 1 ]; then
    echo "FAIL: Duplicate markers found (count: $MARKER_COUNT)"
    exit 1
fi

# Test: ignore --force (replace existing)
echo "Testing: dev ignore node --force"
dev ignore node --force
MARKER_COUNT=$(grep -c "=== dev-utils: node ===" .gitignore)
if [ "$MARKER_COUNT" -ne 1 ]; then
    echo "FAIL: Force should replace, not duplicate (count: $MARKER_COUNT)"
    exit 1
fi

# Test: ignore multiple technologies
echo "Testing: dev ignore macos"
dev ignore macos
grep -q "=== dev-utils: macos ===" .gitignore || { echo "FAIL: macos section not added"; exit 1; }
grep -q ".DS_Store" .gitignore || { echo "FAIL: .DS_Store pattern not added"; exit 1; }

echo "Testing: dev ignore vscode"
dev ignore vscode
grep -q "=== dev-utils: vscode ===" .gitignore || { echo "FAIL: vscode section not added"; exit 1; }

# Verify all sections present
echo "Verifying all sections..."
grep -q "=== dev-utils: node ===" .gitignore || { echo "FAIL: node section missing"; exit 1; }
grep -q "=== dev-utils: macos ===" .gitignore || { echo "FAIL: macos section missing"; exit 1; }
grep -q "=== dev-utils: vscode ===" .gitignore || { echo "FAIL: vscode section missing"; exit 1; }

echo ""
echo "=== Ignore Command Tests: PASSED ==="
