#!/bin/bash
# ##############################################################################
# TEST RUNNER (HOST)
# Generated by DevUtils CLI (https://github.com/fredlackey/devutils-cli)
# ##############################################################################
#
# Convenience script to run tests from the host machine.
# This script wraps docker compose commands for common operations.
#
# Usage:
#   ./testing/test.sh                    # Run all platforms
#   ./testing/test.sh ubuntu             # Run specific platform
#   ./testing/test.sh ubuntu cli         # Run specific test on platform
#   ./testing/test.sh --shell ubuntu     # Open interactive shell
#   ./testing/test.sh --build            # Rebuild images only
#   ./testing/test.sh --clean            # Clean everything
#
# ##############################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Ensure we're in the project directory
cd "$PROJECT_DIR"

# Print usage
usage() {
    echo "Usage: ./testing/test.sh [OPTIONS] [PLATFORM] [TEST_SUITE]"
    echo ""
    echo "Platforms: ubuntu, debian, amazonlinux, fedora, all (default)"
    echo "Test suites: cli, configure, ignore, identity, install"
    echo ""
    echo "Options:"
    echo "  --shell PLATFORM    Open interactive shell in container"
    echo "  --build             Build images without running tests"
    echo "  --clean             Remove containers, volumes, and images"
    echo "  --rebuild           Clean and rebuild everything"
    echo "  --help              Show this help message"
    echo ""
    echo "Examples:"
    echo "  ./testing/test.sh                     # Run all tests on all platforms"
    echo "  ./testing/test.sh ubuntu              # Run all tests on Ubuntu"
    echo "  ./testing/test.sh ubuntu cli          # Run CLI tests on Ubuntu"
    echo "  ./testing/test.sh --shell debian      # Open shell in Debian container"
    echo "  ./testing/test.sh --clean             # Clean up Docker resources"
}

# Build images
build_images() {
    local platform="$1"
    echo -e "${BLUE}Building Docker images...${NC}"

    if [ -n "$platform" ] && [ "$platform" != "all" ]; then
        docker compose -f "$COMPOSE_FILE" build "$platform"
    else
        docker compose -f "$COMPOSE_FILE" build
    fi
}

# Run tests
run_tests() {
    local platform="$1"
    local test_suite="$2"

    echo -e "${BLUE}Running tests...${NC}"
    echo "Platform: ${platform:-all}"
    echo "Test suite: ${test_suite:-all}"
    echo ""

    if [ -n "$platform" ] && [ "$platform" != "all" ]; then
        if [ -n "$test_suite" ]; then
            docker compose -f "$COMPOSE_FILE" run --rm "$platform" \
                /app/testing/scripts/run-tests.sh "$test_suite"
        else
            docker compose -f "$COMPOSE_FILE" run --rm "$platform"
        fi
    else
        docker compose -f "$COMPOSE_FILE" up --build
    fi
}

# Open interactive shell
open_shell() {
    local platform="$1"

    if [ -z "$platform" ]; then
        echo -e "${RED}Error: Platform required for --shell${NC}"
        echo "Usage: ./testing/test.sh --shell PLATFORM"
        exit 1
    fi

    echo -e "${BLUE}Opening shell in $platform container...${NC}"
    docker compose -f "$COMPOSE_FILE" run --rm "$platform" /bin/bash
}

# Clean up
clean_up() {
    echo -e "${YELLOW}Cleaning up Docker resources...${NC}"

    # Stop and remove containers
    docker compose -f "$COMPOSE_FILE" down --volumes --remove-orphans 2>/dev/null || true

    # Remove images
    echo "Removing test images..."
    docker images --filter "reference=*devutils-cli*" -q | xargs -r docker rmi -f 2>/dev/null || true

    # Prune build cache
    echo "Pruning build cache..."
    docker builder prune -f 2>/dev/null || true

    echo -e "${GREEN}Cleanup complete.${NC}"
}

# Main
main() {
    case "$1" in
        --help|-h)
            usage
            exit 0
            ;;
        --shell)
            open_shell "$2"
            ;;
        --build)
            build_images "$2"
            ;;
        --clean)
            clean_up
            ;;
        --rebuild)
            clean_up
            build_images "$2"
            ;;
        *)
            local platform="$1"
            local test_suite="$2"

            # Validate platform if provided
            if [ -n "$platform" ] && [ "$platform" != "all" ]; then
                case "$platform" in
                    ubuntu|debian|amazonlinux|fedora) ;;
                    *)
                        echo -e "${RED}Error: Unknown platform '$platform'${NC}"
                        echo "Valid platforms: ubuntu, debian, amazonlinux, fedora, all"
                        exit 1
                        ;;
                esac
            fi

            run_tests "$platform" "$test_suite"
            ;;
    esac
}

main "$@"
