#!/bin/bash
# ##############################################################################
# REFRESH ENVIRONMENT
# Generated by DevUtils CLI (https://github.com/fredlackey/devutils-cli)
# ##############################################################################
#
# Rebuilds a single platform container from scratch.
# Use this when you want a completely fresh environment.
#
# Usage (from project root):
#   ./testing/scripts/refresh.sh ubuntu       # Refresh Ubuntu container
#   ./testing/scripts/refresh.sh --all        # Refresh all containers
#
# ##############################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMPOSE_FILE="$PROJECT_DIR/testing/docker-compose.yml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

PLATFORM="$1"

if [ -z "$PLATFORM" ]; then
    echo "Usage: ./testing/scripts/refresh.sh PLATFORM"
    echo "       ./testing/scripts/refresh.sh --all"
    echo ""
    echo "Platforms: ubuntu, debian, amazonlinux, fedora"
    exit 1
fi

cd "$PROJECT_DIR"

if [ "$PLATFORM" = "--all" ]; then
    echo -e "${YELLOW}Refreshing ALL containers...${NC}"

    # Stop all containers
    echo "Stopping containers..."
    docker compose -f "$COMPOSE_FILE" down --volumes 2>/dev/null || true

    # Remove all test images
    echo "Removing images..."
    for plat in ubuntu debian amazonlinux fedora; do
        docker rmi "devutils-cli-$plat" 2>/dev/null || true
        docker rmi "testing-$plat" 2>/dev/null || true
    done

    # Rebuild all
    echo "Rebuilding all images..."
    docker compose -f "$COMPOSE_FILE" build --no-cache

    echo -e "${GREEN}All containers refreshed.${NC}"
else
    # Validate platform
    case "$PLATFORM" in
        ubuntu|debian|amazonlinux|fedora) ;;
        *)
            echo -e "${RED}Error: Unknown platform '$PLATFORM'${NC}"
            echo "Valid platforms: ubuntu, debian, amazonlinux, fedora"
            exit 1
            ;;
    esac

    echo -e "${YELLOW}Refreshing $PLATFORM container...${NC}"

    # Stop specific container
    echo "Stopping container..."
    docker compose -f "$COMPOSE_FILE" stop "$PLATFORM" 2>/dev/null || true
    docker compose -f "$COMPOSE_FILE" rm -f "$PLATFORM" 2>/dev/null || true

    # Remove volume
    echo "Removing volume..."
    docker volume rm "testing_test-tmp-$PLATFORM" 2>/dev/null || true

    # Remove image
    echo "Removing image..."
    docker rmi "devutils-cli-$PLATFORM" 2>/dev/null || true
    docker rmi "testing-$PLATFORM" 2>/dev/null || true

    # Rebuild
    echo "Rebuilding image..."
    docker compose -f "$COMPOSE_FILE" build --no-cache "$PLATFORM"

    echo -e "${GREEN}$PLATFORM container refreshed.${NC}"
fi

echo ""
echo "Run tests with:"
echo "  ./testing/test.sh $PLATFORM"
