#!/bin/bash
# ##############################################################################
# FULL INSTALLATION TESTS
# Generated by DevUtils CLI (https://github.com/fredlackey/devutils-cli)
# ##############################################################################
#
# Tests that installers actually install software and verify the result.
# Unlike test-install.sh (dry-run only), this script:
#   1. Runs actual installations via `dev install <tech> --force`
#   2. Verifies installation using each installer's isInstalled() function
#   3. Tests idempotency by running again
#
# Usage:
#   ./test-install-full.sh              # Test all eligible technologies
#   ./test-install-full.sh curl         # Test specific technology
#   ./test-install-full.sh --list       # List testable technologies
#
# ##############################################################################

set -e

# Paths
APP_DIR="/app"
INSTALLS_DIR="$APP_DIR/src/installs"
INSTALLERS_JSON="$INSTALLS_DIR/installers.json"
TEST_PLATFORM="${TEST_PLATFORM:-unknown}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ##############################################################################
# HELPER FUNCTIONS
# ##############################################################################

# Map Docker platform names to installers.json environment names
# Docker uses "amazonlinux" but installers.json uses "amazon_linux"
map_platform() {
  case "$1" in
    amazonlinux) echo "amazon_linux" ;;
    *) echo "$1" ;;
  esac
}

PLATFORM_ENV=$(map_platform "$TEST_PLATFORM")

# Check if a technology is installed using its isInstalled() function
# Returns 0 if installed, 1 if not installed or check failed
is_installed() {
  local tech="$1"
  node -e "
    const installer = require('$INSTALLS_DIR/${tech}.js');
    if (typeof installer.isInstalled === 'function') {
      Promise.resolve(installer.isInstalled()).then(result => {
        process.exit(result ? 0 : 1);
      }).catch(() => process.exit(1));
    } else {
      // No isInstalled function - cannot verify
      console.error('Warning: ${tech} does not export isInstalled()');
      process.exit(2);
    }
  " 2>/dev/null
  return $?
}

# Check if a technology is eligible for the current platform
is_eligible() {
  local tech="$1"
  node -e "
    const installer = require('$INSTALLS_DIR/${tech}.js');
    if (typeof installer.isEligible === 'function') {
      process.exit(installer.isEligible() ? 0 : 1);
    } else {
      process.exit(0); // Assume eligible if no function
    }
  " 2>/dev/null
  return $?
}

# Get list of technologies that support this platform and are ready for testing
get_testable_technologies() {
  node -e "
    const fs = require('fs');
    const data = JSON.parse(fs.readFileSync('$INSTALLERS_JSON'));
    const platform = '$PLATFORM_ENV';
    data
      .filter(t => t.environments && t.environments.includes(platform))
      .filter(t => t.status === 'test-pending' || t.status === 'ready')
      .forEach(t => console.log(t.filename.replace('.js', '')));
  "
}

# Get display name for a technology from installers.json
get_display_name() {
  local tech="$1"
  node -e "
    const fs = require('fs');
    const data = JSON.parse(fs.readFileSync('$INSTALLERS_JSON'));
    const entry = data.find(t => t.filename === '${tech}.js');
    console.log(entry ? entry.name : '${tech}');
  "
}

# Print section header
print_header() {
  echo ""
  echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
  echo -e "${BLUE}  $1${NC}"
  echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
}

# Print test result
print_result() {
  local status="$1"
  local tech="$2"
  local message="$3"

  case "$status" in
    PASS)
      echo -e "  ${GREEN}[PASS]${NC} $tech: $message"
      ;;
    FAIL)
      echo -e "  ${RED}[FAIL]${NC} $tech: $message"
      ;;
    SKIP)
      echo -e "  ${YELLOW}[SKIP]${NC} $tech: $message"
      ;;
    INFO)
      echo -e "  ${BLUE}[INFO]${NC} $tech: $message"
      ;;
  esac
}

# ##############################################################################
# LIST MODE
# ##############################################################################

list_testable() {
  print_header "Testable Technologies for $TEST_PLATFORM ($PLATFORM_ENV)"
  echo ""

  local technologies
  technologies=$(get_testable_technologies)

  if [ -z "$technologies" ]; then
    echo "  No testable technologies found for this platform."
    return
  fi

  local count=0
  for tech in $technologies; do
    local display_name
    display_name=$(get_display_name "$tech")

    local status=""
    if is_installed "$tech" 2>/dev/null; then
      status="${GREEN}(installed)${NC}"
    elif ! is_eligible "$tech" 2>/dev/null; then
      status="${YELLOW}(not eligible)${NC}"
    fi

    echo -e "  - $tech ($display_name) $status"
    ((count++))
  done

  echo ""
  echo "  Total: $count technologies"
}

# ##############################################################################
# TEST SINGLE TECHNOLOGY
# ##############################################################################

test_technology() {
  local tech="$1"
  local display_name
  display_name=$(get_display_name "$tech")

  echo ""
  echo -e "${BLUE}--- Testing: $tech ($display_name) ---${NC}"

  # Check if installer file exists
  if [ ! -f "$INSTALLS_DIR/${tech}.js" ]; then
    print_result "FAIL" "$tech" "Installer file not found"
    return 1
  fi

  # Check if eligible for this platform
  if ! is_eligible "$tech"; then
    print_result "SKIP" "$tech" "Not eligible for $PLATFORM_ENV"
    return 2
  fi

  # Check if already installed
  local is_installed_result
  is_installed "$tech"
  is_installed_result=$?

  if [ "$is_installed_result" -eq 0 ]; then
    print_result "SKIP" "$tech" "Already installed"
    return 2
  elif [ "$is_installed_result" -eq 2 ]; then
    print_result "FAIL" "$tech" "No isInstalled() function - cannot verify"
    return 1
  fi

  # Run actual installation
  print_result "INFO" "$tech" "Running: dev install $tech --force"

  if ! dev install "$tech" --force; then
    print_result "FAIL" "$tech" "Installation command failed"
    return 1
  fi

  # Verify installation succeeded
  if is_installed "$tech"; then
    print_result "PASS" "$tech" "Installed and verified"
  else
    print_result "FAIL" "$tech" "Installation completed but verification failed"
    return 1
  fi

  # Test idempotency - run again, should not fail
  print_result "INFO" "$tech" "Testing idempotency (running again)..."

  if dev install "$tech" --force; then
    print_result "PASS" "$tech" "Idempotent (second run succeeded)"
  else
    print_result "FAIL" "$tech" "Not idempotent (second run failed)"
    return 1
  fi

  return 0
}

# ##############################################################################
# MAIN
# ##############################################################################

main() {
  local target_tech="$1"

  # Handle --list flag
  if [ "$target_tech" = "--list" ] || [ "$target_tech" = "-l" ]; then
    list_testable
    exit 0
  fi

  print_header "Full Installation Tests"
  echo "  Platform: $TEST_PLATFORM ($PLATFORM_ENV)"
  echo "  Date: $(date)"

  local passed=0
  local failed=0
  local skipped=0

  # Get list of technologies to test
  local technologies
  if [ -n "$target_tech" ]; then
    technologies="$target_tech"
  else
    technologies=$(get_testable_technologies)
  fi

  if [ -z "$technologies" ]; then
    echo ""
    echo "  No technologies to test."
    echo "  Run with --list to see available technologies."
    exit 0
  fi

  # Test each technology
  for tech in $technologies; do
    test_technology "$tech"
    local result=$?

    case "$result" in
      0) ((passed++)) ;;
      1) ((failed++)) ;;
      2) ((skipped++)) ;;
    esac
  done

  # Print summary
  print_header "Summary"
  echo -e "  ${GREEN}Passed:${NC}  $passed"
  echo -e "  ${RED}Failed:${NC}  $failed"
  echo -e "  ${YELLOW}Skipped:${NC} $skipped"
  echo ""

  # Exit with error if any tests failed
  if [ "$failed" -gt 0 ]; then
    echo -e "${RED}=== Full Installation Tests: FAILED ===${NC}"
    exit 1
  else
    echo -e "${GREEN}=== Full Installation Tests: PASSED ===${NC}"
    exit 0
  fi
}

main "$@"
