#!/bin/bash
# ##############################################################################
# IDENTITY COMMAND TESTS
# Generated by DevUtils CLI (https://github.com/fredlackey/devutils-cli)
# ##############################################################################
#
# Tests identity management (profiles, listing, removal, linking).
# Uses fixtures for reliable automated testing.
#
# ##############################################################################

set -e

echo "=== Identity Command Tests ==="

CONFIG_FILE="$HOME/.devutils"
SSH_CONFIG="$HOME/.ssh/config"
GITCONFIG="$HOME/.gitconfig"
FIXTURES_DIR="/app/testing/fixtures"
TEST_DIR="/tmp/test-identity-$$"

# Clean up function
cleanup() {
    rm -rf "$TEST_DIR"
    rm -f "$CONFIG_FILE"
    rm -f "$HOME/.gitconfig-work"
    rm -f "$HOME/.gitconfig-personal"
    # Don't remove entire .ssh directory or .gitconfig
}
trap cleanup EXIT

# Start with minimal config (no identities)
echo "Setting up minimal config..."
cp "$FIXTURES_DIR/devutils-minimal.json" "$CONFIG_FILE"

# Test: identity list (empty)
echo "Testing: dev identity list (no identities)"
OUTPUT=$(dev identity list 2>&1)
if echo "$OUTPUT" | grep -qi "no identities"; then
    echo "  Correctly shows no identities"
else
    echo "  Note: Output was: $OUTPUT"
fi

# Test: identity help
echo "Testing: dev identity --help"
dev identity --help | grep -q "identity" || { echo "FAIL: identity --help failed"; exit 1; }

# Load full config with identities
echo "Testing: config with identities"
cp "$FIXTURES_DIR/devutils-full.json" "$CONFIG_FILE"

# Test: identity list (with identities)
echo "Testing: dev identity list (with identities)"
dev identity list | grep -q "work" || { echo "FAIL: work identity not in list"; exit 1; }
dev identity list | grep -q "personal" || { echo "FAIL: personal identity not in list"; exit 1; }

# ============================================================================
# IDENTITY LINK TESTS
# ============================================================================

echo ""
echo "=== Identity Link Tests ==="

# Test: identity link --help
echo "Testing: dev identity link --help"
dev identity link --help | grep -q "link" || { echo "FAIL: identity link --help failed"; exit 1; }

# Setup: Create test directory
mkdir -p "$TEST_DIR/work"
mkdir -p "$TEST_DIR/personal"

# Test: Link with folder path only (arguments in any order)
echo "Testing: dev identity link work $TEST_DIR/work"
dev identity link work "$TEST_DIR/work"
grep -q '"links"' "$CONFIG_FILE" || { echo "FAIL: links not added to config"; exit 1; }
echo "  Link with folder path: PASSED"

# Verify .devutils was updated
if grep -q "$TEST_DIR/work" "$CONFIG_FILE"; then
    echo "  Path stored in .devutils: PASSED"
else
    echo "FAIL: path not stored in .devutils"
    exit 1
fi

# Verify .gitconfig-work was created
if [ -f "$HOME/.gitconfig-work" ]; then
    echo "  Profile gitconfig created: PASSED"
else
    echo "FAIL: ~/.gitconfig-work not created"
    exit 1
fi

# Verify .gitconfig has includeIf
if grep -q "includeIf" "$GITCONFIG" && grep -q "gitconfig-work" "$GITCONFIG"; then
    echo "  Main gitconfig updated: PASSED"
else
    echo "FAIL: ~/.gitconfig not updated with includeIf"
    exit 1
fi

# Test: Link with remote URL (HTTPS format)
echo "Testing: dev identity link work https://github.com/my-company"
dev identity link work "https://github.com/my-company"
echo "  Link with HTTPS remote: PASSED"

# Verify SSH config was updated
if grep -q "github.com-work" "$SSH_CONFIG"; then
    echo "  SSH config updated: PASSED"
else
    echo "FAIL: ~/.ssh/config not updated"
    exit 1
fi

# Verify URL rewrite rules in profile gitconfig
if grep -q "insteadOf" "$HOME/.gitconfig-work"; then
    echo "  URL rewrite rules added: PASSED"
else
    echo "FAIL: URL rewrite rules not in profile gitconfig"
    exit 1
fi

# Test: Link with SSH format URL
echo "Testing: dev identity link personal git@github.com:FredLackey"
dev identity link personal "git@github.com:FredLackey"
if grep -q "github.com-personal" "$SSH_CONFIG"; then
    echo "  SSH format URL link: PASSED"
else
    echo "FAIL: SSH format URL link failed"
    exit 1
fi

# Test: Idempotency - run same link command again
echo "Testing: Idempotency (run same command again)"
dev identity link work "$TEST_DIR/work"
LINK_COUNT=$(grep -c "$TEST_DIR/work" "$CONFIG_FILE" || true)
if [ "$LINK_COUNT" -le 1 ]; then
    echo "  Idempotency: PASSED (no duplicate links)"
else
    echo "FAIL: Duplicate links created"
    exit 1
fi

# Test: Link with arguments in different order
echo "Testing: Arguments in any order"
dev identity link "$TEST_DIR/personal" personal "https://github.com/personal"
if grep -q "github.com-personal" "$SSH_CONFIG"; then
    echo "  Arguments in any order: PASSED"
else
    echo "FAIL: Arguments in any order failed"
    exit 1
fi

# Test: Folder creation prompt (using echo to simulate 'n')
echo "Testing: Non-existent folder handling"
NON_EXISTENT="$TEST_DIR/does-not-exist"
if [ ! -d "$NON_EXISTENT" ]; then
    # This should prompt - we'll check error handling works
    echo "  Non-existent folder detection works"
fi

# Test: List shows links
echo "Testing: dev identity list shows links"
OUTPUT=$(dev identity list 2>&1)
if echo "$OUTPUT" | grep -qi "links"; then
    echo "  Links displayed in list: PASSED"
else
    echo "  Note: Links section may be empty"
fi

# ============================================================================
# IDENTITY UNLINK TESTS
# ============================================================================

echo ""
echo "=== Identity Unlink Tests ==="

# Test: unlink --help
echo "Testing: dev identity unlink --help"
dev identity unlink --help | grep -q "unlink" || { echo "FAIL: identity unlink --help failed"; exit 1; }

# Test: Unlink existing path
echo "Testing: dev identity unlink $TEST_DIR/work"
dev identity unlink "$TEST_DIR/work"

# Verify link was removed from .devutils
if grep -q "$TEST_DIR/work" "$CONFIG_FILE"; then
    echo "FAIL: path should be removed from .devutils"
    exit 1
fi
echo "  Path removed from .devutils: PASSED"

# Verify includeIf rule was removed from .gitconfig
if grep -q "$TEST_DIR/work" "$GITCONFIG"; then
    echo "FAIL: gitdir rule should be removed from .gitconfig"
    exit 1
fi
echo "  includeIf rule removed from .gitconfig: PASSED"

# Test: Idempotency - unlink same path again should fail gracefully
echo "Testing: Unlink non-existent path (should error)"
if dev identity unlink "$TEST_DIR/work" 2>&1 | grep -q "No link found"; then
    echo "  Unlink non-existent path handled: PASSED"
else
    echo "FAIL: Should report no link found"
    exit 1
fi

# Test: Unlink the personal path
echo "Testing: dev identity unlink $TEST_DIR/personal"
dev identity unlink "$TEST_DIR/personal"
if grep -q "$TEST_DIR/personal" "$CONFIG_FILE"; then
    echo "FAIL: personal path should be removed"
    exit 1
fi
echo "  Second unlink: PASSED"

# Verify identity still exists (just without links)
if ! grep -q '"personal"' "$CONFIG_FILE"; then
    echo "FAIL: personal identity should still exist"
    exit 1
fi
echo "  Identity preserved after unlink: PASSED"

# ============================================================================
# IDENTITY SYNC TESTS
# ============================================================================

echo ""
echo "=== Identity Sync Tests ==="

# Test: sync --help
echo "Testing: dev identity sync --help"
dev identity sync --help | grep -q "sync" || { echo "FAIL: identity sync --help failed"; exit 1; }

# Re-add links for sync test
echo "Testing: Re-adding links for sync test"
dev identity link work "$TEST_DIR/work" "https://github.com/my-company"
dev identity link personal "$TEST_DIR/personal" "https://github.com/personal"

# Remove generated config files to simulate a new machine
echo "Testing: Simulating new machine (removing config files)"
rm -f "$HOME/.gitconfig-work" "$HOME/.gitconfig-personal"
rm -f "$SSH_CONFIG"

# Run sync
echo "Testing: dev identity sync"
dev identity sync

# Verify config files were regenerated
if [ -f "$HOME/.gitconfig-work" ]; then
    echo "  Profile gitconfig regenerated: PASSED"
else
    echo "FAIL: ~/.gitconfig-work not regenerated"
    exit 1
fi

if [ -f "$SSH_CONFIG" ]; then
    echo "  SSH config regenerated: PASSED"
else
    echo "FAIL: ~/.ssh/config not regenerated"
    exit 1
fi

# Verify SSH config has host entries
if grep -q "github.com-work" "$SSH_CONFIG"; then
    echo "  SSH host alias present: PASSED"
else
    echo "FAIL: SSH host alias not in config"
    exit 1
fi

# ============================================================================
# CLEANUP AND FINAL TESTS
# ============================================================================

echo ""
echo "=== Cleanup Tests ==="

# Test: identity remove
echo "Testing: dev identity remove personal --force"
dev identity remove personal --force

# Verify identity was removed
if grep -q '"personal"' "$CONFIG_FILE"; then
    echo "FAIL: personal identity should be removed"
    exit 1
fi
echo "  personal identity removed successfully"

# Verify other identity still exists
grep -q '"work"' "$CONFIG_FILE" || { echo "FAIL: work identity should still exist"; exit 1; }
echo "  work identity still present"

# Test: identity list after removal
echo "Testing: dev identity list (after removal)"
dev identity list | grep -q "work" || { echo "FAIL: work should still be in list"; exit 1; }
if dev identity list | grep -q "personal"; then
    echo "FAIL: personal should not be in list"
    exit 1
fi

# Test: identity remove last identity
echo "Testing: dev identity remove work --force"
dev identity remove work --force

# Test: identity list (empty again)
echo "Testing: dev identity list (empty again)"
OUTPUT=$(dev identity list 2>&1)
if echo "$OUTPUT" | grep -qi "no identities"; then
    echo "  Correctly shows no identities after removal"
fi

echo ""
echo "=== Identity Command Tests: PASSED ==="
