#!/bin/bash
# ##############################################################################
# CONFIGURE COMMAND TESTS
# Generated by DevUtils CLI (https://github.com/fredlackey/devutils-cli)
# ##############################################################################
#
# Tests the configure command and config file handling.
# Uses fixtures for reliable automated testing.
#
# ##############################################################################

set -e

echo "=== Configure Command Tests ==="

CONFIG_FILE="$HOME/.devutils"
FIXTURES_DIR="/app/testing/fixtures"

# Clean up any existing config
rm -f "$CONFIG_FILE"

# Test configure --show without config
echo "Testing: dev configure --show (no config)"
dev configure --show 2>&1 | grep -q "No configuration found\|not found" || { echo "FAIL: --show should indicate no config"; exit 1; }

# Test using fixture instead of interactive input
echo "Testing: config file creation (using fixture)"
cp "$FIXTURES_DIR/devutils-minimal.json" "$CONFIG_FILE"

# Verify config file was created
echo "Verifying config file exists..."
if [ ! -f "$CONFIG_FILE" ]; then
    echo "FAIL: Config file was not created"
    exit 1
fi

# Verify config file contains expected data
echo "Verifying config content..."
grep -q '"name": "Test User"' "$CONFIG_FILE" || { echo "FAIL: Name not in config"; exit 1; }
grep -q '"email": "test@example.com"' "$CONFIG_FILE" || { echo "FAIL: Email not in config"; exit 1; }

# Test configure --show with config
echo "Testing: dev configure --show (with config)"
dev configure --show | grep -q "Test User" || { echo "FAIL: --show should display user name"; exit 1; }

# Test dev status with config
echo "Testing: dev status (with config)"
dev status | grep -q "Test User\|test@example.com" || { echo "FAIL: status should show config"; exit 1; }

# Test full config fixture
echo "Testing: full config with identities"
cp "$FIXTURES_DIR/devutils-full.json" "$CONFIG_FILE"

# Verify identities are present
grep -q '"work"' "$CONFIG_FILE" || { echo "FAIL: work identity not in config"; exit 1; }
grep -q '"personal"' "$CONFIG_FILE" || { echo "FAIL: personal identity not in config"; exit 1; }

# Test status shows identities
echo "Testing: dev status shows identities"
dev status | grep -q "work\|personal" || { echo "FAIL: status should show identities"; exit 1; }

# Verify timestamps in config
echo "Verifying timestamps..."
grep -q '"created":' "$CONFIG_FILE" || { echo "FAIL: Missing created timestamp"; exit 1; }
grep -q '"updated":' "$CONFIG_FILE" || { echo "FAIL: Missing updated timestamp"; exit 1; }

# Clean up
rm -f "$CONFIG_FILE"

echo ""
echo "=== Configure Command Tests: PASSED ==="
