#!/bin/bash
# ##############################################################################
# INSTALL COMMAND TESTS
# Generated by DevUtils CLI (https://github.com/fredlackey/devutils-cli)
# ##############################################################################
#
# Tests install scripts (dry-run mode only for safety).
#
# ##############################################################################

set -e

echo "=== Install Command Tests ==="

# Test: install --list
echo "Testing: dev install --list"
dev install --list || echo "  Note: No install scripts may be available yet"

# Test: install without argument
echo "Testing: dev install (no argument)"
if dev install 2>&1 | grep -qi "error\|no package\|usage"; then
    echo "  Correctly shows error/usage without argument"
else
    echo "FAIL: Should show error without package name"
    exit 1
fi

# Test: install unknown package
echo "Testing: dev install unknown-package-xyz"
if dev install unknown-package-xyz --force 2>&1 | grep -qi "error\|unknown\|not found"; then
    echo "  Correctly rejected unknown package"
else
    echo "FAIL: Should reject unknown package"
    exit 1
fi

# Test dry-run for any available install scripts
echo "Testing dry-run mode for available install scripts..."

# Get list of available install scripts
INSTALLS_DIR="/app/src/installs"
if [ -d "$INSTALLS_DIR" ]; then
    for script in "$INSTALLS_DIR"/*.js; do
        if [ -f "$script" ]; then
            name=$(basename "$script" .js)
            echo "Testing: dev install $name --dry-run --force"
            if dev install "$name" --dry-run --force 2>&1; then
                echo "  $name: dry-run OK"
            else
                echo "  $name: dry-run returned non-zero (may be expected)"
            fi
        fi
    done
else
    echo "  No install scripts directory found at $INSTALLS_DIR"
fi

echo ""
echo "=== Install Command Tests: PASSED ==="
