#!/bin/bash
# ##############################################################################
# CLI COMMAND TESTS
# Generated by DevUtils CLI (https://github.com/fredlackey/devutils-cli)
# ##############################################################################
#
# Tests that all CLI commands parse correctly and produce expected output.
#
# ##############################################################################

set -e

echo "=== CLI Command Tests ==="

# Test that dev command exists
echo "Checking 'dev' command exists..."
which dev || { echo "FAIL: dev command not found"; exit 1; }

# Test help output for main command
echo "Testing: dev --help"
dev --help | grep -q "CLI toolkit" || { echo "FAIL: --help missing description"; exit 1; }

# Test version output
echo "Testing: dev --version"
dev --version | grep -q "0.0.0" || { echo "FAIL: --version failed"; exit 1; }

# Test configure help
echo "Testing: dev configure --help"
dev configure --help | grep -q "configure" || { echo "FAIL: configure --help failed"; exit 1; }

# Test status help
echo "Testing: dev status --help"
dev status --help | grep -q "status" || { echo "FAIL: status --help failed"; exit 1; }

# Test install help
echo "Testing: dev install --help"
dev install --help | grep -q "install" || { echo "FAIL: install --help failed"; exit 1; }

# Test ignore help
echo "Testing: dev ignore --help"
dev ignore --help | grep -q "ignore" || { echo "FAIL: ignore --help failed"; exit 1; }

# Test identity help
echo "Testing: dev identity --help"
dev identity --help | grep -q "identity" || { echo "FAIL: identity --help failed"; exit 1; }

# Test completion help
echo "Testing: dev completion --help"
dev completion --help | grep -q "completion" || { echo "FAIL: completion --help failed"; exit 1; }

# Test status runs without config
echo "Testing: dev status (without config)"
dev status || { echo "FAIL: status failed without config"; exit 1; }

# Test ignore --list
echo "Testing: dev ignore --list"
dev ignore --list | grep -q "node\|macos\|docker" || { echo "FAIL: ignore --list failed"; exit 1; }

# Test install --list
echo "Testing: dev install --list"
dev install --list || echo "Note: No install scripts available yet"

echo ""
echo "=== CLI Command Tests: PASSED ==="
